/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/kpi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dashboard KPIs
         * @description Top-level counts and amounts for the home page (DESIGN.md §6.2.1).
         */
        get: operations["kpi_api_kpi_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/loans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Paginated loan list with year/topic/status/person/liaison filters */
        get: operations["list__api_loans_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/loans/{loan_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Loan detail: borrowers, lenders, installments */
        get: operations["detail_api_loans__loan_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/installments/overdue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lender-side unpaid installments past their due date */
        get: operations["overdue_api_installments_overdue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/persons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Paginated person list with Persian-fuzzy search and filters */
        get: operations["list__api_persons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/persons/{person_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Per-person profile */
        get: operations["detail_api_persons__person_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Loan topics with per-year counts + outstanding */
        get: operations["topics_api_topics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Imports history */
        get: operations["imports_list_api_imports_get"];
        put?: never;
        /**
         * Upload one or more xlsm files; processed in background
         * @description Multipart upload endpoint.
         *
         *     For each uploaded file:
         *     - Compute sha256.  If a successful Import already has this sha, return it
         *       (deduped) without touching disk again or scheduling work.
         *     - Otherwise persist the file under ``upload_dir/<sha>.xlsm`` and create
         *       a fresh Import row with ``status=pending``.  Background task does the
         *       actual parse + validate + write.
         *
         *     Returns 202 with the (possibly mixed dedup + pending) list of Import
         *     rows; client polls ``/api/imports/{id}`` until terminal status.
         */
        post: operations["imports_upload_api_imports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/imports/{import_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One import */
        get: operations["imports_detail_api_imports__import_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/issues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** DataIssue rows (defaults to latest import) */
        get: operations["issues_list_api_issues_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/monthly": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Monthly analytics (default = previous completed Jalali month) */
        get: operations["monthly_api_analytics_monthly_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/circulation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whole-history monthly money circulation (installments due vs paid) */
        get: operations["circulation_api_analytics_circulation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness + DB connectivity check.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Version
         * @description Return application version (also reported by /api/health).
         */
        get: operations["version_api_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_imports_upload_api_imports_post */
        Body_imports_upload_api_imports_post: {
            /**
             * Files
             * @description One or more .xlsm files
             */
            files: string[];
        };
        /**
         * CirculationMonth
         * @description One Jalali month of repayment flow (lender-side installments due).
         */
        CirculationMonth: {
            /** Persian Year */
            persian_year: number;
            /** Persian Month */
            persian_month: number;
            /** Label Fa */
            label_fa: string;
            /** Count */
            count: number;
            /** Amount Total */
            amount_total: string;
            /** Amount Paid */
            amount_paid: string;
            /** Amount Unpaid */
            amount_unpaid: string;
        };
        /**
         * CirculationResponse
         * @description Whole-history monthly money circulation, oldest month first.
         */
        CirculationResponse: {
            /** Months */
            months: components["schemas"]["CirculationMonth"][];
        };
        /** DataIssueItem */
        DataIssueItem: {
            /** Id */
            id: number;
            /** Import Id */
            import_id: number;
            severity: components["schemas"]["IssueSeverity"];
            category: components["schemas"]["IssueCategory"];
            /** Message */
            message: string;
            /** Sheet */
            sheet?: string | null;
            /** Cell */
            cell?: string | null;
            /** Context */
            context?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * GuarantorRole
         * @description Ordered slots a person's main + secondary guarantors fill (4 max).
         * @enum {string}
         */
        GuarantorRole: "main" | "secondary_2" | "secondary_3" | "secondary_4";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportDetailResponse */
        ImportDetailResponse: {
            /** Id */
            id: number;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
            /** Source Filename */
            source_filename: string;
            /** Source Sha256 */
            source_sha256: string;
            /** Years Imported */
            years_imported: number[];
            status: components["schemas"]["ImportStatus"];
            /** Duration Ms */
            duration_ms?: number | null;
            /** Error Message */
            error_message?: string | null;
            /** Issue Count */
            issue_count: number;
            /** Error Count */
            error_count: number;
            /** Report */
            report: {
                [key: string]: unknown;
            };
        };
        /** ImportListItem */
        ImportListItem: {
            /** Id */
            id: number;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
            /** Source Filename */
            source_filename: string;
            /** Source Sha256 */
            source_sha256: string;
            /** Years Imported */
            years_imported: number[];
            status: components["schemas"]["ImportStatus"];
            /** Duration Ms */
            duration_ms?: number | null;
            /** Error Message */
            error_message?: string | null;
            /** Issue Count */
            issue_count: number;
            /** Error Count */
            error_count: number;
        };
        /**
         * ImportStatus
         * @description Lifecycle of one xlsm import.
         * @enum {string}
         */
        ImportStatus: "pending" | "running" | "success" | "failed";
        /** InstallmentRef */
        InstallmentRef: {
            /** Due Persian Year */
            due_persian_year: number;
            /** Due Persian Month */
            due_persian_month: number;
            /** Due Day Of Month */
            due_day_of_month: number;
            /** Amount */
            amount: string;
            status: components["schemas"]["InstallmentStatus"];
        };
        /**
         * InstallmentStatus
         * @description Repayment installment state.
         *
         *     Derived from the cell fill colour in the source xlsm (``#00B050`` = paid,
         *     anything else = unpaid).  Phase 2 will add intermediate states once
         *     actual payment dates are recorded.
         * @enum {string}
         */
        InstallmentStatus: "paid" | "unpaid";
        /** InstallmentsDueByDay */
        InstallmentsDueByDay: {
            /** Day */
            day: number;
            /** Count */
            count: number;
            /** Paid Amount */
            paid_amount: string;
            /** Unpaid Amount */
            unpaid_amount: string;
        };
        /** InstallmentsDueSummary */
        InstallmentsDueSummary: {
            /** Count */
            count: number;
            /** Amount Total */
            amount_total: string;
            /** Amount Paid */
            amount_paid: string;
            /** Amount Unpaid */
            amount_unpaid: string;
            /** Payment Rate Pct */
            payment_rate_pct: number;
            /** By Day */
            by_day: components["schemas"]["InstallmentsDueByDay"][];
        };
        /**
         * IssueCategory
         * @description Categorical type of an importer ``DataIssue``.
         *
         *     Open list — extend when the importer learns to detect new problems.
         *     Persian labels live in the frontend i18n map (DESIGN.md §6.5), keyed
         *     off these identifiers.
         * @enum {string}
         */
        IssueCategory: "broken_ref" | "total_mismatch" | "unresolved_person" | "unknown_topic" | "duplicate_phone" | "bad_day" | "color_anomaly" | "unknown_phone_format" | "orphan_row" | "missing_day" | "missing_amount";
        /**
         * IssueSeverity
         * @description Severity bucket for an importer ``DataIssue``.
         * @enum {string}
         */
        IssueSeverity: "error" | "warning" | "info";
        /**
         * KPIByYear
         * @description One row per persian year present in the DB.
         */
        KPIByYear: {
            /** Year */
            year: number;
            /** Loan Count */
            loan_count: number;
            /** Total */
            total: string;
            /** Outstanding */
            outstanding: string;
        };
        /**
         * KPIResponse
         * @description Top-level dashboard KPIs (DESIGN.md §5.2 / §6.2.1).
         */
        KPIResponse: {
            /** Persons Total */
            persons_total: number;
            /** Loans Total */
            loans_total: number;
            /** Loans Active */
            loans_active: number;
            /** Loans Settled */
            loans_settled: number;
            /** Total Amount */
            total_amount: string;
            /** Outstanding Total */
            outstanding_total: string;
            /** Overdue Installments */
            overdue_installments: number;
            /** By Year */
            by_year: components["schemas"]["KPIByYear"][];
        };
        /** LenderPartyRef */
        LenderPartyRef: {
            /** Party Id */
            party_id: number;
            person: components["schemas"]["PersonRef"];
            /** Amount */
            amount: string;
            /** Paid */
            paid: string;
            /** Remaining */
            remaining: string;
            /** Installments */
            installments: components["schemas"]["InstallmentRef"][];
        };
        /**
         * LoanDetailResponse
         * @description Response shape for /api/loans/{id} (DESIGN.md §5.2).
         */
        LoanDetailResponse: {
            /**
             * Loan
             * @description Loan-level fields: id, persian_year, loan_number, channel_number, total_amount, liaison_label, description
             */
            loan?: {
                [key: string]: unknown;
            };
            topic: components["schemas"]["TopicRef"];
            guarantor: components["schemas"]["PersonRef"] | null;
            /** Borrowers */
            borrowers: components["schemas"]["LoanPartyRef"][];
            /** Lenders */
            lenders: components["schemas"]["LenderPartyRef"][];
            totals: components["schemas"]["LoanTotals"];
        };
        /**
         * LoanListItem
         * @description Row on the loans list page (DESIGN.md §6.2.4).
         */
        LoanListItem: {
            /** Id */
            id: number;
            /** Persian Year */
            persian_year: number;
            /** Loan Number */
            loan_number: string;
            /** Channel Number */
            channel_number: string | null;
            /** Topic Name */
            topic_name: string;
            /** Borrower Name */
            borrower_name: string;
            /** Liaison Label */
            liaison_label: string | null;
            /** Total */
            total: string;
            /** Paid */
            paid: string;
            /** Remaining */
            remaining: string;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "settled";
        };
        /** LoanPartyRef */
        LoanPartyRef: {
            /** Party Id */
            party_id: number;
            person: components["schemas"]["PersonRef"];
            /** Amount */
            amount: string;
        };
        /** LoanTotals */
        LoanTotals: {
            /** Total */
            total: string;
            /** Paid */
            paid: string;
            /** Remaining */
            remaining: string;
            /** Settled */
            settled: boolean;
        };
        /** MonthlyAnalyticsResponse */
        MonthlyAnalyticsResponse: {
            period: components["schemas"]["MonthlyPeriod"];
            new_loans: components["schemas"]["NewLoansSummary"];
            installments_due: components["schemas"]["InstallmentsDueSummary"];
            /** New Loans By Topic */
            new_loans_by_topic: components["schemas"]["TopicBreakdownItem"][];
            /** Top Borrowers */
            top_borrowers: components["schemas"]["PersonAmountItem"][];
            /** Top Lenders */
            top_lenders: components["schemas"]["PersonAmountItem"][];
        };
        /** MonthlyPeriod */
        MonthlyPeriod: {
            /** Persian Year */
            persian_year: number;
            /** Persian Month */
            persian_month: number;
            /** Label Fa */
            label_fa: string;
        };
        /** NewLoansSummary */
        NewLoansSummary: {
            /** Count */
            count: number;
            /** Total Amount */
            total_amount: string;
        };
        /**
         * OverdueInstallmentItem
         * @description One overdue installment, fully denormalized for table display.
         */
        OverdueInstallmentItem: {
            /** Installment Id */
            installment_id: number;
            /** Loan Id */
            loan_id: number;
            /** Loan Number */
            loan_number: string;
            /** Persian Year */
            persian_year: number;
            /** Topic Name */
            topic_name: string;
            borrower: components["schemas"]["PersonRef"];
            lender: components["schemas"]["PersonRef"];
            guarantor: components["schemas"]["PersonRef"] | null;
            /** Due Persian Year */
            due_persian_year: number;
            /** Due Persian Month */
            due_persian_month: number;
            /** Due Day Of Month */
            due_day_of_month: number;
            /** Amount */
            amount: string;
            /** Days Overdue */
            days_overdue: number;
        };
        /** Page[DataIssueItem] */
        Page_DataIssueItem_: {
            /** Items */
            items: components["schemas"]["DataIssueItem"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** Page[ImportListItem] */
        Page_ImportListItem_: {
            /** Items */
            items: components["schemas"]["ImportListItem"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** Page[LoanListItem] */
        Page_LoanListItem_: {
            /** Items */
            items: components["schemas"]["LoanListItem"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** Page[OverdueInstallmentItem] */
        Page_OverdueInstallmentItem_: {
            /** Items */
            items: components["schemas"]["OverdueInstallmentItem"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** Page[PersonListItem] */
        Page_PersonListItem_: {
            /** Items */
            items: components["schemas"]["PersonListItem"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** PersonAmountItem */
        PersonAmountItem: {
            /** Person Id */
            person_id: number;
            /** Full Name */
            full_name: string;
            /** Total */
            total: string;
        };
        /** PersonDetailResponse */
        PersonDetailResponse: {
            person: components["schemas"]["PersonListItem"];
            /** Guarantors */
            guarantors: components["schemas"]["PersonGuarantorRef"][];
            /** By Year */
            by_year: components["schemas"]["PersonYearBreakdown"][];
            lifetime: components["schemas"]["PersonLifetime"];
            /** Upcoming */
            upcoming: components["schemas"]["PersonInstallmentRef"][];
            /** Overdue */
            overdue: components["schemas"]["PersonInstallmentRef"][];
        };
        /** PersonGuarantorRef */
        PersonGuarantorRef: {
            role: components["schemas"]["GuarantorRole"];
            person: components["schemas"]["PersonRef"];
        };
        /**
         * PersonInstallmentRef
         * @description An upcoming or overdue installment surfaced on the profile page.
         */
        PersonInstallmentRef: {
            /** Loan Id */
            loan_id: number;
            /** Loan Number */
            loan_number: string;
            /** Counterparty Name */
            counterparty_name: string;
            /** Due Persian Year */
            due_persian_year: number;
            /** Due Persian Month */
            due_persian_month: number;
            /** Due Day Of Month */
            due_day_of_month: number;
            /** Amount */
            amount: string;
            status: components["schemas"]["InstallmentStatus"];
            /** Role */
            role: string;
        };
        /** PersonLifetime */
        PersonLifetime: {
            /** Receivable */
            receivable: string;
            /** Debt */
            debt: string;
            /** Net Capital */
            net_capital: string;
        };
        /**
         * PersonListItem
         * @description Row on the persons list page (DESIGN.md §6.2.2).
         */
        PersonListItem: {
            /** Id */
            id: number;
            /** Full Name */
            full_name: string;
            /** Phone */
            phone: string;
            /** Is Verified */
            is_verified: boolean;
            /** Total Lent */
            total_lent: string;
            /** Total Borrowed */
            total_borrowed: string;
            /** Outstanding Receivable */
            outstanding_receivable: string;
            /** Outstanding Debt */
            outstanding_debt: string;
            /** Net Capital */
            net_capital: string;
        };
        /**
         * PersonRef
         * @description Minimal nested person reference used in profile detail responses.
         */
        PersonRef: {
            /** Id */
            id: number;
            /** Full Name */
            full_name: string;
            /** Phone */
            phone: string;
        };
        /** PersonYearBreakdown */
        PersonYearBreakdown: {
            /** Year */
            year: number;
            /** As Borrower Loans */
            as_borrower_loans: number;
            /** As Borrower Total */
            as_borrower_total: string;
            /** As Borrower Paid */
            as_borrower_paid: string;
            /** As Borrower Remaining */
            as_borrower_remaining: string;
            /** As Lender Parties */
            as_lender_parties: number;
            /** As Lender Total */
            as_lender_total: string;
            /** As Lender Paid */
            as_lender_paid: string;
            /** As Lender Remaining */
            as_lender_remaining: string;
        };
        /** TopicBreakdownItem */
        TopicBreakdownItem: {
            /** Topic Name */
            topic_name: string;
            /** Count */
            count: number;
            /** Total */
            total: string;
        };
        /** TopicRef */
        TopicRef: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /**
         * TopicSummary
         * @description One row on the Topics page (DESIGN.md §6.2.6).
         */
        TopicSummary: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Loan Count */
            loan_count: number;
            /** Total */
            total: string;
            /** Outstanding */
            outstanding: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    kpi_api_kpi_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KPIResponse"];
                };
            };
        };
    };
    list__api_loans_get: {
        parameters: {
            query?: {
                year?: number | null;
                /** @description Comma-separated topic ids, e.g. '3,7' */
                topic_ids?: string | null;
                /** @description active | settled */
                status?: string | null;
                borrower_id?: number | null;
                lender_id?: number | null;
                liaison?: string | null;
                /** @description Substring match on loan_number */
                q?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_LoanListItem_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detail_api_loans__loan_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                loan_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoanDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overdue_api_installments_overdue_get: {
        parameters: {
            query?: {
                min_days_overdue?: number;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_OverdueInstallmentItem_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list__api_persons_get: {
        parameters: {
            query?: {
                /** @description Persian-fuzzy name + phone-substring */
                q?: string | null;
                verified_only?: boolean;
                has_debt?: boolean;
                has_receivable?: boolean;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_PersonListItem_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detail_api_persons__person_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    topics_api_topics_get: {
        parameters: {
            query?: {
                /** @description Filter by Jalali year */
                year?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    imports_list_api_imports_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ImportListItem_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    imports_upload_api_imports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_imports_upload_api_imports_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportListItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    imports_detail_api_imports__import_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                import_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    issues_list_api_issues_get: {
        parameters: {
            query?: {
                import_id?: number | null;
                severity?: components["schemas"]["IssueSeverity"] | null;
                category?: components["schemas"]["IssueCategory"] | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_DataIssueItem_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    monthly_api_analytics_monthly_get: {
        parameters: {
            query?: {
                year?: number | null;
                month?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyAnalyticsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    circulation_api_analytics_circulation_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CirculationResponse"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    version_api_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
