"""init: persons, topics, loans, parties, installments, imports, issues

Revision ID: e934947a132b
Revises:
Create Date: 2026-05-25 09:21:43.464212

"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e934947a132b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # --- extensions ---
    # pg_trgm powers fuzzy Persian name search on person.full_name.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "import",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=False),
        sa.Column("source_filename", sa.String(length=255), nullable=False),
        sa.Column("years_imported", postgresql.ARRAY(sa.Integer()), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "success",
                "failed",
                name="ck_import_status",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column(
            "report", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import")),
    )
    op.create_index(op.f("ix_import_source_sha256"), "import", ["source_sha256"], unique=True)
    op.create_table(
        "loan_topic",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("legacy_num", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_loan_topic")),
    )
    op.create_index(op.f("ix_loan_topic_name"), "loan_topic", ["name"], unique=True)
    op.create_table(
        "person",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("phone_raw", sa.String(length=64), nullable=True),
        sa.Column("national_code", sa.String(length=20), nullable=True),
        sa.Column("messenger", sa.String(length=120), nullable=True),
        sa.Column("is_verified", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_person")),
    )
    op.create_index(op.f("ix_person_national_code"), "person", ["national_code"], unique=True)
    op.create_index(op.f("ix_person_phone"), "person", ["phone"], unique=True)
    op.create_table(
        "data_issue",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("import_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "severity",
            sa.Enum(
                "error",
                "warning",
                "info",
                name="ck_data_issue_severity",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "category",
            sa.Enum(
                "broken_ref",
                "total_mismatch",
                "unresolved_person",
                "unknown_topic",
                "duplicate_phone",
                "bad_day",
                "color_anomaly",
                "unknown_phone_format",
                "orphan_row",
                "missing_day",
                "missing_amount",
                name="ck_data_issue_category",
                native_enum=False,
                create_constraint=True,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("sheet", sa.String(length=120), nullable=True),
        sa.Column("cell", sa.String(length=40), nullable=True),
        sa.Column("context", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["import_id"],
            ["import.id"],
            name=op.f("fk_data_issue_import_id_import"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_issue")),
    )
    op.create_index(
        "ix_data_issue_import_severity", "data_issue", ["import_id", "severity"], unique=False
    )
    op.create_table(
        "loan",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("persian_year", sa.SmallInteger(), nullable=False),
        sa.Column("loan_number", sa.String(length=32), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("topic_id", sa.Integer(), nullable=False),
        sa.Column("import_id", sa.BigInteger(), nullable=False),
        sa.Column("channel_number", sa.String(length=32), nullable=True),
        sa.Column("guarantor_id", sa.BigInteger(), nullable=True),
        sa.Column("liaison_label", sa.String(length=80), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("total_amount > 0", name=op.f("ck_loan_total_amount_positive")),
        sa.ForeignKeyConstraint(
            ["guarantor_id"],
            ["person.id"],
            name=op.f("fk_loan_guarantor_id_person"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["import_id"], ["import.id"], name=op.f("fk_loan_import_id_import"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["loan_topic.id"],
            name=op.f("fk_loan_topic_id_loan_topic"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_loan")),
        sa.UniqueConstraint("persian_year", "loan_number", name="unique_year_number"),
    )
    op.create_index(op.f("ix_loan_guarantor_id"), "loan", ["guarantor_id"], unique=False)
    op.create_index(op.f("ix_loan_liaison_label"), "loan", ["liaison_label"], unique=False)
    op.create_index(op.f("ix_loan_persian_year"), "loan", ["persian_year"], unique=False)
    op.create_index(op.f("ix_loan_topic_id"), "loan", ["topic_id"], unique=False)
    op.create_table(
        "person_guarantor",
        sa.Column("person_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "main",
                "secondary_2",
                "secondary_3",
                "secondary_4",
                name="ck_person_guarantor_role",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("guarantor_id", sa.BigInteger(), nullable=False),
        sa.CheckConstraint(
            "person_id <> guarantor_id", name=op.f("ck_person_guarantor_self_guarantee_forbidden")
        ),
        sa.ForeignKeyConstraint(
            ["guarantor_id"],
            ["person.id"],
            name=op.f("fk_person_guarantor_guarantor_id_person"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["person.id"],
            name=op.f("fk_person_guarantor_person_id_person"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("person_id", "role", name=op.f("pk_person_guarantor")),
    )
    op.create_index(
        op.f("ix_person_guarantor_guarantor_id"), "person_guarantor", ["guarantor_id"], unique=False
    )
    op.create_table(
        "loan_party",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("loan_id", sa.BigInteger(), nullable=False),
        sa.Column("person_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "borrower",
                "lender",
                name="ck_loan_party_role",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("display_order", sa.SmallInteger(), nullable=False),
        sa.CheckConstraint("amount > 0", name=op.f("ck_loan_party_amount_positive")),
        sa.ForeignKeyConstraint(
            ["loan_id"], ["loan.id"], name=op.f("fk_loan_party_loan_id_loan"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["person.id"],
            name=op.f("fk_loan_party_person_id_person"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_loan_party")),
        sa.UniqueConstraint("loan_id", "role", "person_id", name="unique_role_person"),
    )
    op.create_index("ix_loan_party_loan_role", "loan_party", ["loan_id", "role"], unique=False)
    op.create_index("ix_loan_party_person_role", "loan_party", ["person_id", "role"], unique=False)
    op.create_table(
        "installment",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("loan_party_id", sa.BigInteger(), nullable=False),
        sa.Column("due_persian_year", sa.SmallInteger(), nullable=False),
        sa.Column("due_persian_month", sa.SmallInteger(), nullable=False),
        sa.Column("due_day_of_month", sa.SmallInteger(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "paid",
                "unpaid",
                name="ck_installment_status",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("paid_persian_year", sa.SmallInteger(), nullable=True),
        sa.Column("paid_persian_month", sa.SmallInteger(), nullable=True),
        sa.Column("paid_persian_day", sa.SmallInteger(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "(paid_persian_year IS NULL) = (paid_persian_month IS NULL) AND (paid_persian_year IS NULL) = (paid_persian_day IS NULL)",
            name=op.f("ck_installment_paid_date_triple_consistent"),
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_installment_amount_positive")),
        sa.CheckConstraint(
            "due_day_of_month BETWEEN 1 AND 31", name=op.f("ck_installment_due_day_valid")
        ),
        sa.CheckConstraint(
            "due_persian_month BETWEEN 1 AND 12", name=op.f("ck_installment_due_month_valid")
        ),
        sa.CheckConstraint(
            "paid_persian_day IS NULL OR paid_persian_day BETWEEN 1 AND 31",
            name=op.f("ck_installment_paid_day_valid"),
        ),
        sa.CheckConstraint(
            "paid_persian_month IS NULL OR paid_persian_month BETWEEN 1 AND 12",
            name=op.f("ck_installment_paid_month_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["loan_party_id"],
            ["loan_party.id"],
            name=op.f("fk_installment_loan_party_id_loan_party"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_installment")),
    )
    op.create_index(
        "ix_installment_party_status", "installment", ["loan_party_id", "status"], unique=False
    )
    op.create_index(
        "ix_installment_unpaid_due",
        "installment",
        ["due_persian_year", "due_persian_month", "due_day_of_month"],
        unique=False,
        postgresql_where=sa.text("status = 'unpaid'"),
    )
    # ### end Alembic commands ###

    # --- trigram GIN index on person.full_name (autogenerate can't infer) ---
    # Powers the dashboard's name search with fuzzy / partial Persian match.
    op.execute("CREATE INDEX ix_person_full_name_trgm ON person USING gin (full_name gin_trgm_ops)")


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS ix_person_full_name_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_installment_unpaid_due",
        table_name="installment",
        postgresql_where=sa.text("status = 'unpaid'"),
    )
    op.drop_index("ix_installment_party_status", table_name="installment")
    op.drop_table("installment")
    op.drop_index("ix_loan_party_person_role", table_name="loan_party")
    op.drop_index("ix_loan_party_loan_role", table_name="loan_party")
    op.drop_table("loan_party")
    op.drop_index(op.f("ix_person_guarantor_guarantor_id"), table_name="person_guarantor")
    op.drop_table("person_guarantor")
    op.drop_index(op.f("ix_loan_topic_id"), table_name="loan")
    op.drop_index(op.f("ix_loan_persian_year"), table_name="loan")
    op.drop_index(op.f("ix_loan_liaison_label"), table_name="loan")
    op.drop_index(op.f("ix_loan_guarantor_id"), table_name="loan")
    op.drop_table("loan")
    op.drop_index("ix_data_issue_import_severity", table_name="data_issue")
    op.drop_table("data_issue")
    op.drop_index(op.f("ix_person_phone"), table_name="person")
    op.drop_index(op.f("ix_person_national_code"), table_name="person")
    op.drop_table("person")
    op.drop_index(op.f("ix_loan_topic_name"), table_name="loan_topic")
    op.drop_table("loan_topic")
    op.drop_index(op.f("ix_import_source_sha256"), table_name="import")
    op.drop_table("import")
    # ### end Alembic commands ###

    op.execute("DROP EXTENSION IF EXISTS pg_trgm")
